### ISSUE TITLE
Swagger definition not working

### ISSUE THREAD

**Issue by favetelinguis** [betfair/stream-api-sample-code#3]
Trying the swagger definiton with http://editor.swagger.io/#/ produces lots of errors...

**Comment by bfapi** [comment]
We haven't been able to reproduce any errors when importing the current master version of the swagger definition. Please could you provide details of specific errors you are seeing and where?

Thank you.

**Comment by favetelinguis** [comment]
Looks like thy fixed the editor, now things are working
