### ISSUE TITLE
ECONNRESET on the js example code

### ISSUE THREAD

**Issue by AntouanK** [betfair/stream-api-sample-code#4]
Hi.

I got the swagger schema and used the editor to generate the JS code.
The example I'm given to try : 
```
var BetfairExchangeStreamingApi = require('betfair_exchange_streaming_api');

var api = new BetfairExchangeStreamingApi.DefaultApi()

var requestMessage = new BetfairExchangeStreamingApi.AllRequestTypesExample(); // {AllRequestTypesExample} Requests are sent to socket


var callback = function(error, data, response) {
  if (error) {
    console.error(error);
  } else {
    console.log('API called successfully. Returned data: ' + data);
  }
};
api.requestPost(requestMessage, callback);
```
gives back this : 

```
{ Error: socket hang up
    at createHangUpError (_http_client.js:345:15)
    at Socket.socketOnEnd (_http_client.js:437:23)
    at emitNone (events.js:110:20)
    at Socket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: 'ECONNRESET', response: undefined }
```

Any idea why I'm getting this error?

**Comment by bfapi** [comment]
Hello Antonis,

You are trying to make a HTTP POST I guess. You should open a persistent TCP connection instead (use socket.io or whatever is appropriate on nodeJS).

Take a look on the documentation it might answer future questions you have: http://docs.developer.betfair.com/docs/display/1smk3cen4v3lu3yomq5qye0ni/Exchange+Stream+API

**Comment by AntouanK** [comment]
On the same page, at the "swagger" section ( http://docs.developer.betfair.com/docs/display/1smk3cen4v3lu3yomq5qye0ni/Exchange+Stream+API#ExchangeStreamAPI-SwaggerDefinition ) you suggested to download the schema json, load it in the swagger editor, and use the code generation.

That's what I did.
And in the zip I got back, there's a README that suggests to do `npm install` and then run the snippet of code I posted above.

So I'm not intentionally making a POST call, I was just trying to follow the README.

I do understand it's a socket, so a POST call is not the right way.

Would you like to help me get a socket connection test running on node so you can then have that as a README for anyone else that tries to use it with JS?

~I could use https://www.npmjs.com/package/ws I think.~
I don't need websockets, so I'll look up how to connect so a simple SSL socket with node.

Just to clarify, if I open the connection myself, and then write/send the requests and parse the responses, where do I use the code generated from swagger?
I thought that code is supposed to abstract those request/response writing.

**Comment by AntouanK** [comment]
So, I managed to get a TLS socket connection.

I'm using my appKey and session ( I use https://developers.betfair.com/visualisers/api-ng-sports-operations/ to validate that they are right ) but in the socket connection I get this response when I try to authenticate:

```
{"op":"status","statusCode":"FAILURE","errorCode":"NOT_AUTHORIZED","errorMessage":"AppKey is not configured for service","connectionClosed":true,"connectionId":"501-280917101124-111606"}
```

Do I have to enable my username somehow?
( http://forum.bdp.betfair.com/showthread.php?t=3238 )

**Comment by bfapi** [comment]
Hi Antonis,

Your application key has not permission to access the stream. Please contact bdp@betfair.com.

Thank you

**Comment by AntouanK** [comment]
@bfapi This is the reply I got.

```
The bdp@betfair.com e-mail address is no longer in use.
 
Please direct any Developer Support queries via the provided SUBMIT A TICKET form which is available via https://developer.betfair.com/support/
 
Kind Regards
 
Betfair Developer Program
```

So that email is not longer in use??

**Comment by bfapi** [comment]
Apparently, please follow the instructions given in the auto-response. Thank you
